ME_ID: '4'

TM_ID: 0

PA_ID: 4

# CUDA_ID: 0

Methods:
  {'0':'FGSM',
   # '1':'BIM',
   '2':'MIFGSM',
   '3':'PGD',
   '4':'NES',
   # '5':'DeepFool',
   # '6':'CW',
   '7':'SimBA',
   # '8':'SparseFool',
   '9':'CDP',
   '10':'AdvGAN',
   '11':'GAP',
   '12':'GUAP',
   # '13':'AdvPatch',
   '14':'Square',
   # '15':'DIFGSM',
   '16':'Pixle'
   }

Parameters:
  {'FGSM':[[0.005],[0.01],[0.02],[0.04],[0.08]], #eps
   'BIM':[ #eps, alpha, steps
          [0.01,0.001,10],
          [0.03,0.002,10],
          [0.05,0.004,10],
          [0.08,0.008,10],
          [0.1,0.01,10]
          ],
   'MIFGSM':[ #eps, alpha, steps, decay
          [0.01,0.001,10,0.98],
          [0.03,0.002,10,0.98],
          [0.05,0.004,10,0.98],
          [0.08,0.008,10,0.98],
          [0.1,0.01,10,0.98]
          ],
   'PGD':[ #eps, alpha, steps
          [0.01,0.001,10,0.98],
          [0.03,0.002,10,0.98],
          [0.05,0.004,10,0.98],
          [0.08,0.008,10,0.98],
          [0.1,0.01,10,0.98]
          ],
   'NES':[ #eps, aplha, steps
          [0.04,0.01,30],
          [0.1,0.01,30],
          [0.2,0.02,30],
          [0.4,0.04,30],
          [0.5,0.05,30]], 
   'CW':[[1,100]], #c, steps
   'SimBA':[[0.2,2000,True],
            [0.5,1000,True],
            [0.8,1000,True],
            [0.2,2000,False],
            [0.5,1000,False],
            [0.8,1000,False],
            ], # eps, steps, early_stop
   'SparseFool':[[10,0.8],
                 [10,0.5]], #steps, lam
   'CDP':[[0.01,'checkpoints/cdp_incv3.pth'],
          [0.02,'checkpoints/cdp_incv3.pth']],
   'AdvGAN':[
             [8,'checkpoints/AdvGAN_8.pth'],
             [16,'checkpoints/AdvGAN_16.pth'],
             [4,'checkpoints/AdvGAN_8.pth'],
             [2,'checkpoints/AdvGAN_8.pth'],
             [4,'checkpoints/AdvGAN_16.pth'],], #eps, checkpoint
   'Square':[ # norm, eps, p_init
             ['Linf',0.01],
             ['Linf',0.03],
             ['Linf',0.06],
             ['L2',5],
             ['L2',10],
             ['L2',20]

   ],
   'UAP':[],
   'GAP':[['Uni','./checkpoints/GAP_Uni_805.pth'],
          ['Uni','./checkpoints/GAP_Uni_-1.pth'],
          ['imdep','./checkpoints/GAP_imdep_-1.pth']],
   'FFF':[],
   'GUAP':[['./checkpoints/GUAP_incv3_flow.npy','./checkpoints/GUAP_incv3_noise.npy','st'],
           ['./checkpoints/GUAP_incv3_flow.npy','./checkpoints/GUAP_incv3_noise.npy','noise'],
           ['./checkpoints/GUAP_incv3_flow.npy','./checkpoints/GUAP_incv3_noise.npy','perb']],
   'DeepFool':[[50,0.02],[50,0.2]],
   'AdvPatch':[['./checkpoints/AdvPatch_0.02_859'],
               ['./checkpoints/AdvPatch_0.05_859'],
               ['./checkpoints/AdvPatch_0.1_859'],
               ],
    'DIFGSM':[[0.01,0.001,10,0.98],
              [0.03,0.003,10,0.98],
              [0.05,0.005,10,0.98],
              [0.08,0.008,10,0.98],
              [0.1,0.01,10,0.98]],
     'SPSA':[[0.03,0.01,10]],
     'Pixle':[[[0.1,0.2],10,50]]
   }

Target_Models:
  ['inception_v3','resnet18','desnet','efficientnet']

Image_Size:
  [299,299]

Image_Dir:
  './REF-V1'

Save_Dir:
  ''

Test_Amount: 1000